language: android
sudo: false
before_install:
 - chmod +x gradlew
install:
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
android:
  components:
    - tools
    - build-tools-26
    - platform-tools
    - extra-android-m2repository
    - extra-google-android-support

    # The SDK version used to compile your project
    - android-25

    # Additional components

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-25
jdk: oraclejdk8
os:
  - linux