language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    # The BuildTools version used by your project
    - build-tools-26

    # The SDK version used to compile your project
    - android-25

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-25
    - sys-img-armeabi-v7a-android-19
jdk:
  - oraclejdk8
notifications:
  # webhooks
  webhooks: https://discordapp.com/api/webhooks/332530653440770048/-oZ1JcdaJ4bmGxiK8GvCalAB-c8Y6nZjerYQ-MJkYbiMzi58ItdsMgGECj5FCFONLQxk/slack